#!/bin/bash
# =============================================================================
# Job: eminus_10GeV_geo0_beam0
# Generated by parametric simulation system
# Job ID: 21
# =============================================================================

# Configuration summary:
# - Geometry ID: 0
# - Particle: e-
# - Energy: 10*GeV
# - Beam profile: point
# - Events: 1000

set -e  # Exit on error

# -----------------------------------------------------------------------------
# Environment setup
# -----------------------------------------------------------------------------
echo "Setting up environment..."
cd /afs/cern.ch/user/${USER:0:1}/${USER}/prototype_simulation/DD4SHiP
source /cvmfs/sft.cern.ch/lcg/views/LCG_105/x86_64-el9-gcc13-opt/setup.sh
source install/bin/thisdd4hep.sh

# -----------------------------------------------------------------------------
# Prepare geometry
# -----------------------------------------------------------------------------
WORK_DIR=$(mktemp -d)
echo "Working directory: $WORK_DIR"

# Copy geometry files
cp -r DDDetectors/shipdetectors/* $WORK_DIR/
cp generated_jobs/geometries/ProtoECALBars_geo0.xml $WORK_DIR/Detectors/PID/Prototypes/ProtoECALBars.xml

cd $WORK_DIR

# -----------------------------------------------------------------------------
# Run simulation
# -----------------------------------------------------------------------------
echo "Starting simulation: eminus_10GeV_geo0_beam0"
echo "Events: 1000"

ddsim --compactFile=./Caloprototype.xml \
      --runType=batch \
      -G \
      -N=1000 \
      --steeringFile steering.py \
      --outputFile=eminus_10GeV_geo0_beam0.root \
      --gun.particle "e-" \
      --gun.energy "10*GeV" \
      --gun.position "0.0 0.0 -110.0*cm" \
      --gun.direction "0.0 0.1 1.0" \
      --gun.isotrop false \
      --part.userParticleHandler=""

# -----------------------------------------------------------------------------
# Copy output
# -----------------------------------------------------------------------------
OUTPUT_DIR="/eos/user/${USER:0:1}/${USER}/splitcal_sim/outputs"
mkdir -p $OUTPUT_DIR
cp eminus_10GeV_geo0_beam0.root $OUTPUT_DIR/

# Cleanup
cd /tmp
rm -rf $WORK_DIR

echo "Job eminus_10GeV_geo0_beam0 completed successfully"
echo "Output: $OUTPUT_DIR/eminus_10GeV_geo0_beam0.root"
