#!/bin/bash
# =============================================================================
# Job: muminus_3GeV_geo0_beam1
# Generated by parametric simulation system
# Job ID: 58
# =============================================================================

# Configuration summary:
# - Geometry ID: 0
# - Particle: mu-
# - Energy: 3*GeV
# - Beam profile: isotropic
# - Events: 1000

set -e  # Exit on error

# -----------------------------------------------------------------------------
# Environment setup
# -----------------------------------------------------------------------------
echo "Setting up environment..."
cd /afs/cern.ch/user/${USER:0:1}/${USER}/prototype_simulation/DD4SHiP
source /cvmfs/sft.cern.ch/lcg/views/LCG_105/x86_64-el9-gcc13-opt/setup.sh
source install/bin/thisdd4hep.sh

# -----------------------------------------------------------------------------
# Prepare geometry
# -----------------------------------------------------------------------------
WORK_DIR=$(mktemp -d)
echo "Working directory: $WORK_DIR"

# Copy geometry files
cp -r DDDetectors/shipdetectors/* $WORK_DIR/
cp generated_jobs/geometries/ProtoECALBars_geo0.xml $WORK_DIR/Detectors/PID/Prototypes/ProtoECALBars.xml

cd $WORK_DIR

# -----------------------------------------------------------------------------
# Run simulation
# -----------------------------------------------------------------------------
echo "Starting simulation: muminus_3GeV_geo0_beam1"
echo "Events: 1000"

ddsim --compactFile=./Caloprototype.xml \
      --runType=batch \
      -G \
      -N=1000 \
      --steeringFile steering.py \
      --outputFile=muminus_3GeV_geo0_beam1.root \
      --gun.particle "mu-" \
      --gun.energy "3*GeV" \
      --gun.position "0.0 0.0 -110.0*cm" \
      --gun.isotrop true \
      --gun.thetaMin "0*deg" \
      --gun.thetaMax "5*deg" \
      --gun.phiMin "0*deg" \
      --gun.phiMax "360*deg" \
      --gun.distribution "uniform" \
      --part.userParticleHandler=""

# -----------------------------------------------------------------------------
# Copy output
# -----------------------------------------------------------------------------
OUTPUT_DIR="/eos/user/${USER:0:1}/${USER}/splitcal_sim/outputs"
mkdir -p $OUTPUT_DIR
cp muminus_3GeV_geo0_beam1.root $OUTPUT_DIR/

# Cleanup
cd /tmp
rm -rf $WORK_DIR

echo "Job muminus_3GeV_geo0_beam1 completed successfully"
echo "Output: $OUTPUT_DIR/muminus_3GeV_geo0_beam1.root"
