jobs:
- id: 0
  name: eminus_1GeV_geo0_beam0
- id: 1
  name: eminus_1GeV_geo0_beam1
- id: 2
  name: eminus_1GeV_geo0_beam2
- id: 3
  name: eminus_1GeV_geo0_beam0
- id: 4
  name: eminus_1GeV_geo0_beam1
- id: 5
  name: eminus_1GeV_geo0_beam2
- id: 6
  name: eminus_3GeV_geo0_beam0
- id: 7
  name: eminus_3GeV_geo0_beam1
- id: 8
  name: eminus_3GeV_geo0_beam2
- id: 9
  name: eminus_3GeV_geo0_beam0
- id: 10
  name: eminus_3GeV_geo0_beam1
- id: 11
  name: eminus_3GeV_geo0_beam2
- id: 12
  name: eminus_5GeV_geo0_beam0
- id: 13
  name: eminus_5GeV_geo0_beam1
- id: 14
  name: eminus_5GeV_geo0_beam2
- id: 15
  name: eminus_5GeV_geo0_beam0
- id: 16
  name: eminus_5GeV_geo0_beam1
- id: 17
  name: eminus_5GeV_geo0_beam2
- id: 18
  name: eminus_10GeV_geo0_beam0
- id: 19
  name: eminus_10GeV_geo0_beam1
- id: 20
  name: eminus_10GeV_geo0_beam2
- id: 21
  name: eminus_10GeV_geo0_beam0
- id: 22
  name: eminus_10GeV_geo0_beam1
- id: 23
  name: eminus_10GeV_geo0_beam2
- id: 24
  name: piplus_1GeV_geo0_beam0
- id: 25
  name: piplus_1GeV_geo0_beam1
- id: 26
  name: piplus_1GeV_geo0_beam2
- id: 27
  name: piplus_1GeV_geo0_beam0
- id: 28
  name: piplus_1GeV_geo0_beam1
- id: 29
  name: piplus_1GeV_geo0_beam2
- id: 30
  name: piplus_3GeV_geo0_beam0
- id: 31
  name: piplus_3GeV_geo0_beam1
- id: 32
  name: piplus_3GeV_geo0_beam2
- id: 33
  name: piplus_3GeV_geo0_beam0
- id: 34
  name: piplus_3GeV_geo0_beam1
- id: 35
  name: piplus_3GeV_geo0_beam2
- id: 36
  name: piplus_5GeV_geo0_beam0
- id: 37
  name: piplus_5GeV_geo0_beam1
- id: 38
  name: piplus_5GeV_geo0_beam2
- id: 39
  name: piplus_5GeV_geo0_beam0
- id: 40
  name: piplus_5GeV_geo0_beam1
- id: 41
  name: piplus_5GeV_geo0_beam2
- id: 42
  name: piplus_10GeV_geo0_beam0
- id: 43
  name: piplus_10GeV_geo0_beam1
- id: 44
  name: piplus_10GeV_geo0_beam2
- id: 45
  name: piplus_10GeV_geo0_beam0
- id: 46
  name: piplus_10GeV_geo0_beam1
- id: 47
  name: piplus_10GeV_geo0_beam2
- id: 48
  name: muminus_1GeV_geo0_beam0
- id: 49
  name: muminus_1GeV_geo0_beam1
- id: 50
  name: muminus_1GeV_geo0_beam2
- id: 51
  name: muminus_1GeV_geo0_beam0
- id: 52
  name: muminus_1GeV_geo0_beam1
- id: 53
  name: muminus_1GeV_geo0_beam2
- id: 54
  name: muminus_3GeV_geo0_beam0
- id: 55
  name: muminus_3GeV_geo0_beam1
- id: 56
  name: muminus_3GeV_geo0_beam2
- id: 57
  name: muminus_3GeV_geo0_beam0
- id: 58
  name: muminus_3GeV_geo0_beam1
- id: 59
  name: muminus_3GeV_geo0_beam2
- id: 60
  name: muminus_5GeV_geo0_beam0
- id: 61
  name: muminus_5GeV_geo0_beam1
- id: 62
  name: muminus_5GeV_geo0_beam2
- id: 63
  name: muminus_5GeV_geo0_beam0
- id: 64
  name: muminus_5GeV_geo0_beam1
- id: 65
  name: muminus_5GeV_geo0_beam2
- id: 66
  name: muminus_10GeV_geo0_beam0
- id: 67
  name: muminus_10GeV_geo0_beam1
- id: 68
  name: muminus_10GeV_geo0_beam2
- id: 69
  name: muminus_10GeV_geo0_beam0
- id: 70
  name: muminus_10GeV_geo0_beam1
- id: 71
  name: muminus_10GeV_geo0_beam2
parameters:
  energies:
  - 1*GeV
  - 3*GeV
  - 5*GeV
  - 10*GeV
  n_events: 1000
  particles:
  - e-
  - pi+
  - mu-
total_jobs: 72
unique_geometries: 1
